[Distribution]
Repositories=epel
Distribution=alma

[Build]
SandboxTrees=
    mkosi.conf.d/repos/gnome-backport.repo:/etc/yum.repos.d/gnome-backport.repo

[Content]
Packages=
    gnome-shell
    gdm
    mutter
    gnome-session
    nautilus
    gnome50-el10-compat
    selinux-policy
    # gnome-initial-setup